# SPDX-License-Identifier: Apache-2.0
# Copyright Contributors to the ODPi Egeria project.
name: "Merge (Java8, Maven)"

# Trigger after code is merged. only on main repo
# - does not run on modification (may be just text)

on:
  push:
    branches: [master,egeria-release-*,feature-*]
  
jobs:
  build:
    runs-on: ubuntu-latest
    name: "Merge"
    steps:
      - uses: actions/checkout@v2
        name: Checkout source
        # Only for a merge into this repo - not a fork
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          distribution: 'zulu'
          java-version: '11'
      - name: Cache Gradle packages
        uses: actions/cache@v2.1.4
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle
      # Only for a merge into this repo - not a fork, and just for the main branch
      - name: Build (Publish snapshots to maven central)
         if: ${{ github.repository == 'odpi/egeria-connector-sas-viya' && github.ref == 'refs/heads/main'}}
         # TODO: Need to extend build to make use of snapshot repo for publishing
         run: ./gradlew build
      # In other cases just build but don't publish
      - name: Build (no snapshots)
        if: ${{ github.repository != 'odpi/egeria-connector-sas-viya' || github.ref != 'refs/heads/main'}}
        run: ./gradlew build
      # --
      - name: Upload Connector
          uses: actions/upload-artifact@v2
          with:
            name: Connector
            path: build/libs/*.jar